### ISSUE TITLE
Achievements chart on Portfolio page is not updated

### ISSUE THREAD

**Issue by tuyetlinhnguyen** [rhodyprog4ds/BrownFall21#21]
The achievements listed on the Portfolio Dates and Key Facts page is outdated compared to the Data Science Achievements page under Syllabus.

**Comment by brownsarahm** [comment]
I just updated for check 3 date wise, but I don't see what's different.  Is it the description of the skills that different?  Have you refreshed the page?  They're generated from the same source (there's a .yml file I read into a dataFrame and print out segments of), so it shouldn't be possible for the definitions to be out of sync.

**Comment by tuyetlinhnguyen** [comment]
When I looked at the page during class, I think I saw the Portfolio Dates and Key Facts had a table that listed all the achievements and marked which ones where checked in each portfolio submission. It was the same as the table under the "Portfolios and Skills" section in the Data Science Achievements page, except it was missing newer skills, like workflow, representation, etc. It looks fine now though.

**Comment by brownsarahm** [comment]
oh, the table on the "Portfolio Dates and Key Facts" page was only displaying the the rows that were eligible in check 2 but also had the columns to show which would stay eligible for 3 & 4.  Ill make a note to hide the other columns/ link to the full table next time
