### ISSUE TITLE
question: About the About folder for CSC 310 Assignment 1

### ISSUE THREAD

**Issue by MJSher** [rhodyprog4ds/BrownFall21#27]
@rhodyprog4ds/instructors

One of the steps in assignment 1 is to "Add a Jupyter notebook called grading.ipynb to the about folder and write a function that computes a grade for this course, with the docstring below." However, I do not know what about folder is being referred to. I know of an about *file* in my portfolio repository, but not a folder. Am I supposed to create my own About folder, and if so, should it be in my portfolio repository? Please help me on this situation as I am massively confused by it.

**Comment by brownsarahm** [comment]
this is for fall 21
