### ISSUE TITLE
question: [topic of your question]

### ISSUE THREAD

**Issue by Flurry58** [rhodyprog4ds/BrownFall21#28]
Enter your question here, please leave both of us tagged. 
If it's a general question about the instructions, consider asking it on the website repo to help others instead.
I tried to add to the website repo but it did not let me so I am adding it here.
I am consfused on the first question you asked in the about.md
What are you refering to when you say "include a 3 sentence summary of the most important points you want me to
remember from the following". I don't know what the following is as after this comment you ask a different question. Thank you

**Comment by brownsarahm** [comment]
This is from fall 2021, not current.
